/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IGasDiscountExtension } from "../IGasDiscountExtension";

export class IGasDiscountExtension__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGasDiscountExtension {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IGasDiscountExtension;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gasUsed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "flags",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "calldataLength",
        type: "uint256",
      },
    ],
    name: "calculateGas",
    outputs: [
      {
        internalType: "contract IChi",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];
