/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IOneSplitMultiInterface extends ethers.utils.Interface {
  functions: {
    "getExpectedReturn(address,address,uint256,uint256,uint256)": FunctionFragment;
    "getExpectedReturnWithGas(address,address,uint256,uint256,uint256,uint256)": FunctionFragment;
    "getExpectedReturnWithGasMulti(address[],uint256,uint256[],uint256[],uint256[])": FunctionFragment;
    "swap(address,address,uint256,uint256,uint256[],uint256)": FunctionFragment;
    "swapMulti(address[],uint256,uint256,uint256[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getExpectedReturn",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedReturnWithGas",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedReturnWithGasMulti",
    values: [
      string[],
      BigNumberish,
      BigNumberish[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapMulti",
    values: [
      string[],
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getExpectedReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedReturnWithGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedReturnWithGasMulti",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapMulti", data: BytesLike): Result;

  events: {};
}

export class IOneSplitMulti extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IOneSplitMultiInterface;

  functions: {
    getExpectedReturn(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber[]] & {
        returnAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    "getExpectedReturn(address,address,uint256,uint256,uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber[]] & {
        returnAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    getExpectedReturnWithGas(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      destTokenEthPriceTimesGasPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber[]] & {
        returnAmount: BigNumber;
        estimateGasAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    "getExpectedReturnWithGas(address,address,uint256,uint256,uint256,uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      destTokenEthPriceTimesGasPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber[]] & {
        returnAmount: BigNumber;
        estimateGasAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    getExpectedReturnWithGasMulti(
      tokens: string[],
      amount: BigNumberish,
      parts: BigNumberish[],
      flags: BigNumberish[],
      destTokenEthPriceTimesGasPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber, BigNumber[]] & {
        returnAmounts: BigNumber[];
        estimateGasAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    "getExpectedReturnWithGasMulti(address[],uint256,uint256[],uint256[],uint256[])"(
      tokens: string[],
      amount: BigNumberish,
      parts: BigNumberish[],
      flags: BigNumberish[],
      destTokenEthPriceTimesGasPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber, BigNumber[]] & {
        returnAmounts: BigNumber[];
        estimateGasAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    swap(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "swap(address,address,uint256,uint256,uint256[],uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    swapMulti(
      tokens: string[],
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "swapMulti(address[],uint256,uint256,uint256[],uint256[])"(
      tokens: string[],
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  getExpectedReturn(
    fromToken: string,
    destToken: string,
    amount: BigNumberish,
    parts: BigNumberish,
    flags: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber[]] & {
      returnAmount: BigNumber;
      distribution: BigNumber[];
    }
  >;

  "getExpectedReturn(address,address,uint256,uint256,uint256)"(
    fromToken: string,
    destToken: string,
    amount: BigNumberish,
    parts: BigNumberish,
    flags: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber[]] & {
      returnAmount: BigNumber;
      distribution: BigNumber[];
    }
  >;

  getExpectedReturnWithGas(
    fromToken: string,
    destToken: string,
    amount: BigNumberish,
    parts: BigNumberish,
    flags: BigNumberish,
    destTokenEthPriceTimesGasPrice: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber[]] & {
      returnAmount: BigNumber;
      estimateGasAmount: BigNumber;
      distribution: BigNumber[];
    }
  >;

  "getExpectedReturnWithGas(address,address,uint256,uint256,uint256,uint256)"(
    fromToken: string,
    destToken: string,
    amount: BigNumberish,
    parts: BigNumberish,
    flags: BigNumberish,
    destTokenEthPriceTimesGasPrice: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber[]] & {
      returnAmount: BigNumber;
      estimateGasAmount: BigNumber;
      distribution: BigNumber[];
    }
  >;

  getExpectedReturnWithGasMulti(
    tokens: string[],
    amount: BigNumberish,
    parts: BigNumberish[],
    flags: BigNumberish[],
    destTokenEthPriceTimesGasPrices: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], BigNumber, BigNumber[]] & {
      returnAmounts: BigNumber[];
      estimateGasAmount: BigNumber;
      distribution: BigNumber[];
    }
  >;

  "getExpectedReturnWithGasMulti(address[],uint256,uint256[],uint256[],uint256[])"(
    tokens: string[],
    amount: BigNumberish,
    parts: BigNumberish[],
    flags: BigNumberish[],
    destTokenEthPriceTimesGasPrices: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], BigNumber, BigNumber[]] & {
      returnAmounts: BigNumber[];
      estimateGasAmount: BigNumber;
      distribution: BigNumber[];
    }
  >;

  swap(
    fromToken: string,
    destToken: string,
    amount: BigNumberish,
    minReturn: BigNumberish,
    distribution: BigNumberish[],
    flags: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "swap(address,address,uint256,uint256,uint256[],uint256)"(
    fromToken: string,
    destToken: string,
    amount: BigNumberish,
    minReturn: BigNumberish,
    distribution: BigNumberish[],
    flags: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  swapMulti(
    tokens: string[],
    amount: BigNumberish,
    minReturn: BigNumberish,
    distribution: BigNumberish[],
    flags: BigNumberish[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "swapMulti(address[],uint256,uint256,uint256[],uint256[])"(
    tokens: string[],
    amount: BigNumberish,
    minReturn: BigNumberish,
    distribution: BigNumberish[],
    flags: BigNumberish[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getExpectedReturn(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber[]] & {
        returnAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    "getExpectedReturn(address,address,uint256,uint256,uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber[]] & {
        returnAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    getExpectedReturnWithGas(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      destTokenEthPriceTimesGasPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber[]] & {
        returnAmount: BigNumber;
        estimateGasAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    "getExpectedReturnWithGas(address,address,uint256,uint256,uint256,uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      destTokenEthPriceTimesGasPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber[]] & {
        returnAmount: BigNumber;
        estimateGasAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    getExpectedReturnWithGasMulti(
      tokens: string[],
      amount: BigNumberish,
      parts: BigNumberish[],
      flags: BigNumberish[],
      destTokenEthPriceTimesGasPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber, BigNumber[]] & {
        returnAmounts: BigNumber[];
        estimateGasAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    "getExpectedReturnWithGasMulti(address[],uint256,uint256[],uint256[],uint256[])"(
      tokens: string[],
      amount: BigNumberish,
      parts: BigNumberish[],
      flags: BigNumberish[],
      destTokenEthPriceTimesGasPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber, BigNumber[]] & {
        returnAmounts: BigNumber[];
        estimateGasAmount: BigNumber;
        distribution: BigNumber[];
      }
    >;

    swap(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "swap(address,address,uint256,uint256,uint256[],uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapMulti(
      tokens: string[],
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "swapMulti(address[],uint256,uint256,uint256[],uint256[])"(
      tokens: string[],
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getExpectedReturn(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getExpectedReturn(address,address,uint256,uint256,uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getExpectedReturnWithGas(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      destTokenEthPriceTimesGasPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getExpectedReturnWithGas(address,address,uint256,uint256,uint256,uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      destTokenEthPriceTimesGasPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getExpectedReturnWithGasMulti(
      tokens: string[],
      amount: BigNumberish,
      parts: BigNumberish[],
      flags: BigNumberish[],
      destTokenEthPriceTimesGasPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getExpectedReturnWithGasMulti(address[],uint256,uint256[],uint256[],uint256[])"(
      tokens: string[],
      amount: BigNumberish,
      parts: BigNumberish[],
      flags: BigNumberish[],
      destTokenEthPriceTimesGasPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swap(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "swap(address,address,uint256,uint256,uint256[],uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    swapMulti(
      tokens: string[],
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "swapMulti(address[],uint256,uint256,uint256[],uint256[])"(
      tokens: string[],
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getExpectedReturn(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getExpectedReturn(address,address,uint256,uint256,uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getExpectedReturnWithGas(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      destTokenEthPriceTimesGasPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getExpectedReturnWithGas(address,address,uint256,uint256,uint256,uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      parts: BigNumberish,
      flags: BigNumberish,
      destTokenEthPriceTimesGasPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getExpectedReturnWithGasMulti(
      tokens: string[],
      amount: BigNumberish,
      parts: BigNumberish[],
      flags: BigNumberish[],
      destTokenEthPriceTimesGasPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getExpectedReturnWithGasMulti(address[],uint256,uint256[],uint256[],uint256[])"(
      tokens: string[],
      amount: BigNumberish,
      parts: BigNumberish[],
      flags: BigNumberish[],
      destTokenEthPriceTimesGasPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swap(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "swap(address,address,uint256,uint256,uint256[],uint256)"(
      fromToken: string,
      destToken: string,
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    swapMulti(
      tokens: string[],
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "swapMulti(address[],uint256,uint256,uint256[],uint256[])"(
      tokens: string[],
      amount: BigNumberish,
      minReturn: BigNumberish,
      distribution: BigNumberish[],
      flags: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
