# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'ALCHEMY_API_KEY' # [Required]
          value: ${{secrets.ALCHEMY_API_KEY}}
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: test # will run `yarn test` command
